// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library dartdoc.html_printer_test;

import 'package:dartdoc/src/html_printer.dart';
import 'package:unittest/unittest.dart';

void main() {
  group('HtmlPrinter', () {
    test('basic', () {
      HtmlPrinter printer = new HtmlPrinter();
      printer.start(title: "FooBar");
      printer.end();
      expect(_normalize(printer.toString()),
          '<!DOCTYPE html> <!-- generated by dartdoc --> <html> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>FooBar</title> </head> <body> </body> </html>');
    });

    test('tag', () {
      HtmlPrinter printer = new HtmlPrinter();
      printer.start(title: "FooBar");
      printer.tag('foo',
          contents: "text", classes: "clazz", href: "http://www.cheese.com");
      printer.end();
      expect(_normalize(printer.toString()),
          '<!DOCTYPE html> <!-- generated by dartdoc --> <html> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>FooBar</title> </head> <body> <foo class="clazz" href="http://www.cheese.com">text</foo> </body> </html>');
    });

    test('startTag / endTag', () {
      HtmlPrinter printer = new HtmlPrinter();
      printer.start(title: "FooBar");
      printer.startTag('foo', classes: "clazz");
      printer.endTag();
      printer.end();
      expect(_normalize(printer.toString()),
          '<!DOCTYPE html> <!-- generated by dartdoc --> <html> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>FooBar</title> </head> <body> <foo class="clazz"> </foo> </body> </html>');
    });

    test('reset', () {
      HtmlPrinter printer = new HtmlPrinter();
      printer.start(title: "FooBar");
      printer.end();
      printer.reset();
      printer.start(title: "FooBar2");
      printer.end();
      expect(_normalize(printer.toString()),
          '<!DOCTYPE html> <!-- generated by dartdoc --> <html> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>FooBar2</title> </head> <body> </body> </html>');
    });
  });
}

String _normalize(String str) => str.replaceAll(new RegExp(r'\s+'), ' ').trim();
