# Dependabot configuration file.
version: 2

updates:
  # Enable weekly pubspec.yaml dependencies checks.
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "type-infra"

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - autosubmit
    groups:
      github-actions:
        patterns:
          - "*"
