analyzer:
  strong-mode: true
  language:
    enableGenericMethods: true
    enablePreviewDart2: true
    enableSuperMixins: true
  exclude:
    - 'doc/**'
    - 'lib/templates/*.html'
    - 'pub.dartlang.org/**'
    - 'testing/**'
linter:
  rules:
    - annotate_overrides
    - avoid_init_to_null
    - directives_ordering
    - no_adjacent_strings_in_list
    - package_api_docs
    - slash_for_doc_comments
    - prefer_final_fields
#    - unnecessary_brace_in_string_interps
