# Change analysis_options.yaml and analysis_options_presubmit.yaml
# together.
include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: ignore
    unused_import: warning
    unused_shown_name: warning
  language:
    strict-raw-types: true
  exclude:
    - 'doc/**'
    - 'lib/src/third_party/pkg/**'
    - 'lib/templates/*.html'
    - 'pub.dartlang.org/**'
    - 'testing/**'
    - 'testing/flutter_packages/test_package_flutter_plugin/**'
    - 'testing/test_package_export_error/**'
linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    avoid_init_to_null: true
    directives_ordering: true
    no_adjacent_strings_in_list: true
    package_api_docs: true
    prefer_final_fields: true
    prefer_initializing_formals: true
    prefer_void_to_null: true
    slash_for_doc_comments: true
    type_annotate_public_apis: true
    # Work in progress canonical score lints
    unawaited_futures: true
