# Change analysis_options.yaml and analysis_options_presubmit.yaml
# together.
include: package:lints/recommended.yaml

analyzer:
  errors:
    todo: ignore
    unused_import: warning
    unused_shown_name: warning
  language:
    # TODO(srawlins) Enable strict-casts.
    # strict-casts: true
    strict-raw-types: true
    strict-inference: true
  exclude:
    - 'doc/**'
    - 'testing/**'

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - directives_ordering
    - no_adjacent_strings_in_list
    - omit_local_variable_types
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_super_parameters
