builders:
  resourceBuilder:
    import: "../../../tool/builder.dart"
    builder_factories: ["resourceBuilder"]
    build_extensions: {'$lib$': ['src/html/resources.g.dart']}
    build_to: "source"
    auto_apply: none

targets:
  dartdoc:
    sources: []
    dependencies: [dartdoc:resources]

  builder:
    sources: ["tool/builder.dart"]

  resources:
    # Switch to just "lib/resources/**" after https://github.com/dart-lang/build/issues/1575
    # is fixed.
    sources: {include:["lib/resources/**", "lib/$lib$"]}
    dependencies: [dartdoc:builder]
    builders: {"dartdoc|resourceBuilder": {enabled: true}}
