builders:
  resource_builder:
    import: "tool/builder.dart"
    builder_factories: ["resourceBuilder"]
    build_extensions: {'$lib$': ['src/generator/html_resources.g.dart']}
    build_to: "source"
    auto_apply: none
  mustachio_builder:
    import: "tool/mustachio/builder.dart"
    builder_factories: ["mustachioBuilder"]
    build_extensions:
      ".dart":
        - ".aot_renderers_for_html.dart"
        - ".aot_renderers_for_md.dart"
        - ".runtime_renderers.dart"
    build_to: "source"

targets:
  builder:
    auto_apply_builders: false
    sources:
      - tool/builder.dart
      - tool/mustachio/builder.dart
  testing:
    auto_apply_builders: false
    sources:
      exclude:
        - tool/builder.dart
        - tool/mustachio/builder.dart
    builders:
      dartdoc:mustachio_builder:
        enabled: true
        generate_for:
          - test/mustachio/foo.dart
        options:
          rendererClassesArePublic: true
      build_test:test_bootstrap:
        enabled: false
      build_version:build_version:
        enabled: false

  $default:
    dependencies:
      - :testing
    sources:
      exclude:
        - tool/builder.dart
        - tool/mustachio/builder.dart
    builders:
      build_version:
        enabled: true
      dartdoc:resource_builder:
        enabled: true
      dartdoc:mustachio_builder:
        enabled: true
        generate_for: ["lib/src/generator/templates.dart"]
