builders:
  resource_builder:
    import: "tool/builder.dart"
    builder_factories: ["resourceBuilder"]
    build_extensions: {'$lib$': ['src/generator/html_resources.g.dart']}
    build_to: "source"
    auto_apply: none

targets:
  builder:
    sources: ["tool/builder.dart"]

  $default:
    sources:
      exclude: ["tool/builder.dart"]
    builders:
      build_version:
        enabled: true
      dartdoc|resource_builder:
        enabled: true
