builders:
  resource_builder:
    import: "tool/builder.dart"
    builder_factories: ["resourceBuilder"]
    build_extensions: {'$lib$': ['src/generator/html_resources.g.dart']}
    build_to: "source"
    auto_apply: none
  mustachio_builder:
    import: "lib/src/mustachio/builder.dart"
    builder_factories: ["mustachioBuilder"]
    build_extensions: {".dart": [".renderers.dart"]}
    build_to: "source"

targets:
  builder:
    sources:
      - tool/builder.dart
      - lib/src/mustachio/builder.dart

  $default:
    sources:
      exclude:
        - tool/builder.dart
        - lib/src/mustachio/builder.dart
    builders:
      build_version:
        enabled: true
      dartdoc|resource_builder:
        enabled: true
      dartdoc|mustachio_builder:
        enabled: true
        generate_for: ["lib/src/generator/templates.dart"]
