name: test_package_flutter_plugin
version: 0.1.0
description: A happy flutter almost plugin being documented
homepage: http://github.com/dart-lang/dartdoc/tree/master/testing/test_package_flutter_plugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
